export const APP_STATE = 'Bubble Gobble V1';
export const X = '✖';
export const GAME_PAGE = 'GAME PAGE';
export const MIN_BLOB_RADIUS = 10;
export const PAGE_PAD = 10;
export const PAD = 12;
export const CORNER_RADIUS = 100;
export const PROMPT_START_OVER = 'Start over?';
export const PROMPT_RESET_STATS = 'Reset stats?';
export const THRESHOLD = 5;
export const PCT = 50;
export const ORB_RADIUS = 7;
export const PPT = 4;   // pixels per tick